update envs_user_manage

diff --git a/bin/envs_user_manage b/bin/envs_user_manage
--- a/bin/envs_user_manage
+++ b/bin/envs_user_manage
@@ -22,12 +22,24 @@ head_def="$head_mime\r\n$head_type"
 
 ###
 
+send_db_mail() {
+	db_type="$1"
+	db_sub="Subject: database on envs created"
+	db_mail="$head_def\r\nTo: $user@$domain\r\nFrom: sudoers@$domain\r\n$db_sub"
+
+	echo -e "$db_mail\r\n$(sed -e s/_username_/"$user"/g -e s/_password_/"$newpw"/g -e s/_sql_/"$db_type"/g /usr/local/bin/envs.net/database-email.tmpl)" \
+		| sendmail "$user"@"$domain"
+}
+
+
 add_user_mysql_db() {
 	mysql -u root << EOM
 CREATE DATABASE $user ;
 GRANT ALL PRIVILEGES ON $user.* TO '$user'@'localhost' IDENTIFIED BY '$newpw' ;
 FLUSH PRIVILEGES ;
 EOM
+
+	send_db_mail mysql
 }
 
 del_user_mysql_db() {
@@ -41,10 +53,13 @@ EOM
 
 add_user_pgsql_db() {
 	sudo -u postgres psql <<EOM
-CREATE USER $user WITH PASSWORD '$newpw' ;
+CREATE USER $user ;
+ALTER USER $user WITH PASSWORD '$newpw';
 CREATE DATABASE $user ENCODING 'UTF8' LC_COLLATE='C' LC_CTYPE='C' template=template0 OWNER $user ;
-GRANT ALL PRIVILEGES ON DATABASE $user to $user ;
+GRANT ALL PRIVILEGES ON DATABASE $user TO $user ;
 EOM
+
+	send_db_mail pgsql
 }
 
 del_user_pgsql_db() {
@@ -55,6 +70,7 @@ DROP USER $user ;
 EOM
 }
 
+###
 
 add_user() {
 	useradd -m -g 9999 -s /bin/bash -p "$pwcrypt" "$user"
@@ -81,7 +97,7 @@ add_user() {
 	chown -R "$user":"$short_dom" /home/"$user"/.ssh
 
 	# setup database
-	add_user_mysql_db
+	#add_user_mysql_db
 	#add_user_pgsql_db
 
 	# setup email mailbox
@@ -95,7 +111,7 @@ add_user() {
 	readme_sub="Subject: Welcome ~$user | please readme!"
 	readme_mail="$head_def\r\nTo: $mailTo\r\nCC: $user@$domain\r\nFrom: sudoers@$domain\r\n$readme_sub"
 
-	echo -e "$readme_mail\r\n$(cat /usr/local/bin/envs.net/welcome-readme.tmpl)" | sendmail "$user"@"$domain"
+	echo -e "$readme_mail\r\n$(cat /usr/local/bin/envs.net/welcome-readme.tmpl)" | sendmail "$user"@"$domain" "$mailTo"
 
 	sleep 1
 
@@ -133,28 +149,43 @@ add_user() {
 
 	# announcing new user on mastodon
 	sudo -u services toot post "welcome new user ~$user"
+
+	# cleanup current signup
+	sed -i /"$user"/d /var/signups_current
 }
 
 del_user() {
 	# unsubscribe mailing list
 	# ??
 	echo -e "$head_def\r\nTo: team-leave@$domain\r\nFrom: $user@$domain\r\nSubject: leave\r\n" | sudo -u "$user" sendmail team-leave@"$domain"
+
+	# stop user stuff
+	pgrep -u "$user"
+	ps -fp "$(pgrep -u $user)"
+	killall -KILL -u "$user"
+
 	# remove user
-	deluser --remove-home "$user"
+	userdel -rf "$user"
+
 	# unset user quota
 	rm /etc/security/limits.d/"$user"
+
 	# unset mail aliases
 	sed -i /"$user"/d /etc/aliases
 	sed -i /"$user"/d /etc/email-addresses
+
 	# remove email mailbox
 	# get userid from lxc-attach
 	mail_userid=$(lxc-attach -n mail -- bash -c "/usr/local/bin/coreapi action accounts list -p search=$user@$domain | jq '.[] | .pk'")
 	lxc-attach -n mail -- bash -c "/usr/local/bin/coreapi action accounts delete -p id=$mail_userid"
+
 	# remove database
 	del_user_mysql_db
-	#del_user_pgsql_db
+	del_user_pgsql_db
+
 	# unlink gemini
 	[ -L /var/gemini/\~"$user" ] && unlink /var/gemini/\~"$user"
+
 	# remove znc account
 	printf '\n!!! ADMIN: please remove %s also from lists.%s and znc.%s !!!\n\n' "$user" "$domain" "$domain"
 }
@@ -186,11 +217,37 @@ case "$cmd" in
 		fi
   ;;
 
+
+  add_mysql)	[ $# -lt 2 ] && printf 'not enough args\n' && exit 1
+				add_user_mysql_db
+  ;;
+
+  del_mysql)	[ $# -lt 2 ] && printf 'not enough args\n' && exit 1
+				del_user_mysql_db
+  ;;
+
+#  add_pqsql)	[ $# -lt 2 ] && printf 'not enough args\n' && exit 1
+#				add_user_pgsql_db
+#  ;;
+
+#  del_pqsql)	[ $# -lt 2 ] && printf 'not enough args\n' && exit 1
+#				del_user_pgsql_db
+#  ;;
+
+
   *)	printf '%s | User Account Setup\n\n' "$domain"
 		printf 'Usage: %s\n  Add a User:\n' "$(basename "$0")"
 		printf '\t%s add "username" "email" "ssh-pubkey"\n' "$(basename "$0")"
 		printf '  Delete a User:\n'
-		printf '\t%s del "username"\n' "$(basename "$0")"
+		printf '\t%s del "username"\n\n' "$(basename "$0")"
+		printf '  create mysql db for User:\n'
+		printf '\t%s add_mysql "username"\n' "$(basename "$0")"
+		printf '  delete mysql db for User:\n'
+		printf '\t%s del_mysql "username"\n\n' "$(basename "$0")"
+		printf '  create pgsql db for User:\n'
+		printf '\t%s add_pgsql "username"\n' "$(basename "$0")"
+		printf '  delete pgsql db for User:\n'
+		printf '\t%s del_pgsql "username"\n' "$(basename "$0")"
   ;;
 esac
 
