fix envs_toot

diff --git a/bin/envs_toot b/bin/envs_toot
--- a/bin/envs_toot
+++ b/bin/envs_toot
@@ -1,8 +1,4 @@
-#!/usr/bin/env sh
-
-if [ "$(id -u)" -ne 0 ] || [ "$(id -u)" -ne 10000 ]; then
-	printf 'sorry only root and creme can toot as envs.\n' && exit 1
-fi
+#!/usr/bin/env bash
 
 print_usage() {
 	printf 'usage: envs_toot "your message"\n\n'
@@ -10,14 +6,20 @@ print_usage() {
 	exit 1
 }
 
-printf 'mastodon-toot as envs.net\n\n'
+if [ "$(id -u)" -eq 0 ] || [ "$(id -u)" -eq 10000 ] ; then
 
-if [ "$1" = '-h' ] || [ "$1" = '--help' ] || [ "$1" = '?' ]; then
-	print_usage
-elif [ -n "$1" ] && [ -z "$2" ]; then
-	sudo -u services /usr/bin/toot post "$(id -un) | $1"
+	printf 'mastodon-toot as envs.net\n\n'
+
+	if [ "$1" = '-h' ] || [ "$1" = '--help' ] || [ "$1" = '?' ]; then
+		print_usage
+	elif [ -n "$1" ] && [ -z "$2" ]; then
+		sudo -u services /usr/bin/toot post "$(id -un) | $1"
+	else
+		print_usage
+	fi
+
 else
-	print_usage
+	printf 'sorry only root and creme can toot as envs.\n' && exit 1
 fi
 
 exit 0
